import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/app/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` antialiased bg-gray-100`}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
